library farm_lab_mobile.globals;

import 'package:farm_lab_mobile/services/network_helper.dart';
import 'package:farm_lab_mobile/services/node_helper.dart';

String token = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWRpZW5jZSI6ImF1ZDoqIiwiaXNzdWVyIjoiRmFybUxhYlRlYW0iLCJzdWIiOiI1ZGM0MjJkNTNiMWUyMjAwMTRhZDNhNmEiLCJpYXQiOjE1NzM4MDY3NzcsImV4cCI6MTU3Mzg5MzE3N30.rUza2mRVvUfMIQFowjrOVTHFeTVhgtEAyL84tOPb8p0';
NetworkHelper networkHelper = NetworkHelper(token);
NodeHelper nodeHelper = NodeHelper(networkHelper);